### ISSUE TITLE
my.startAPVerify 定义文件和文档不一致

### ISSUE THREAD

**Issue by xin2014** [ant-mini-program/api-typings#3]
[my.startAPVerify](https://github.com/ant-mini-program/api-typings/blob/aad95fd87a7d7c7364fb90b68f9cdf76722298b2/packages/my/types/lib.my.d.ts#L8629)

文档地址:
https://opendocs.alipay.com/mini/02osif

![image](https://user-images.githubusercontent.com/7124907/170005723-214566ce-756c-4527-9d2d-b98237c663ec.png)
![image](https://user-images.githubusercontent.com/7124907/170005612-3f6d8a30-c241-47e2-8faa-90efcb4f7f7c.png)

**Comment by bytemain** [comment]
已经定位到问题，明天发个版本修一下~
