### ISSUE TITLE
Wrong type definition in lib.my.d.ts

### ISSUE THREAD

**Issue by gek64** [ant-mini-program/api-typings#30]
https://github.com/ant-mini-program/api-typings/blob/e508d075a86b6410363a13996326ba3371a6db03/packages/my/types/lib.my.d.ts#L20559

According to this [API docs](https://github.com/AlipayDocs/open-docs/blob/ec649416dd2a2c665169087c1e3d618fd5603df3/mini/api/%E5%9F%BA%E7%A1%80API/%E6%96%87%E4%BB%B6/FileSystemManager/FileSystemManager.saveFile.md?plain=1#L66), the type should be a `string`, not a `boolean`. The following code using it as a string works fine.

```ts
handleDownload(): void {
        let fs = my.getFileSystemManager()
        my.downloadFile({
            url: "https://assets.msn.cn/staticsb/statics/latest/widget/LoadingImg.gif",
            success(res1: { apFilePath: string, tempFilePath: string }): void {
                fs.saveFile({
                    tempFilePath: res1.tempFilePath,
                    // @ts-ignore
                    filePath: `${my.env.USER_DATA_PATH}/LoadingImg.gif`,
                    success(res2: my.ISaveFileResponse): void {
                        console.log(res2)
                    }
                })
            }
        })
    }
```

same issue
https://github.com/ant-mini-program/api-typings/blob/e508d075a86b6410363a13996326ba3371a6db03/packages/my/types/lib.my.d.ts#L11069

**Comment by bytemain** [comment]
Thanks for reporting this, I will check it later.

**Comment by bytemain** [comment]
Successfully published:
 - @mini-types/aliauto@3.0.1
 - @mini-types/alipay@3.0.1
 - @mini-types/global@3.0.1
 - @mini-types/my@3.0.1

- https://github.com/ant-mini-program/api-typings/commit/2c2a1143710de2d547722c2194a35314cdd38036
