### ISSUE TITLE
Wrong type definition in lib.my.d.ts

### ISSUE THREAD

**Issue by gek64** [ant-mini-program/api-typings#32]
According to the api documentation of these *Sync functions, their return values should not be `void`.

https://github.com/ant-mini-program/api-typings/blob/a98ab78cc376abf22aea5ce9cc1e03c54d7ca62c/packages/my/types/lib.my.d.ts#L10347
https://github.com/ant-mini-program/api-typings/blob/a98ab78cc376abf22aea5ce9cc1e03c54d7ca62c/packages/my/types/lib.my.d.ts#L10353
https://github.com/ant-mini-program/api-typings/blob/a98ab78cc376abf22aea5ce9cc1e03c54d7ca62c/packages/my/types/lib.my.d.ts#L11590
https://github.com/ant-mini-program/api-typings/blob/a98ab78cc376abf22aea5ce9cc1e03c54d7ca62c/packages/my/types/lib.my.d.ts#L11596
https://github.com/ant-mini-program/api-typings/blob/a98ab78cc376abf22aea5ce9cc1e03c54d7ca62c/packages/my/types/lib.my.d.ts#L10438
https://github.com/ant-mini-program/api-typings/blob/a98ab78cc376abf22aea5ce9cc1e03c54d7ca62c/packages/my/types/lib.my.d.ts#L10444
https://github.com/ant-mini-program/api-typings/blob/a98ab78cc376abf22aea5ce9cc1e03c54d7ca62c/packages/my/types/lib.my.d.ts#L10534
https://github.com/ant-mini-program/api-typings/blob/a98ab78cc376abf22aea5ce9cc1e03c54d7ca62c/packages/my/types/lib.my.d.ts#L10540
https://github.com/ant-mini-program/api-typings/blob/a98ab78cc376abf22aea5ce9cc1e03c54d7ca62c/packages/my/types/lib.my.d.ts#L10731
https://github.com/ant-mini-program/api-typings/blob/a98ab78cc376abf22aea5ce9cc1e03c54d7ca62c/packages/my/types/lib.my.d.ts#L10737
https://github.com/ant-mini-program/api-typings/blob/a98ab78cc376abf22aea5ce9cc1e03c54d7ca62c/packages/my/types/lib.my.d.ts#L11152
https://github.com/ant-mini-program/api-typings/blob/a98ab78cc376abf22aea5ce9cc1e03c54d7ca62c/packages/my/types/lib.my.d.ts#L11158
https://github.com/ant-mini-program/api-typings/blob/a98ab78cc376abf22aea5ce9cc1e03c54d7ca62c/packages/my/types/lib.my.d.ts#L11060
https://github.com/ant-mini-program/api-typings/blob/a98ab78cc376abf22aea5ce9cc1e03c54d7ca62c/packages/my/types/lib.my.d.ts#L11067
https://github.com/ant-mini-program/api-typings/blob/a98ab78cc376abf22aea5ce9cc1e03c54d7ca62c/packages/my/types/lib.my.d.ts#L11388
https://github.com/ant-mini-program/api-typings/blob/a98ab78cc376abf22aea5ce9cc1e03c54d7ca62c/packages/my/types/lib.my.d.ts#L11394
https://github.com/ant-mini-program/api-typings/blob/a98ab78cc376abf22aea5ce9cc1e03c54d7ca62c/packages/my/types/lib.my.d.ts#L10347
https://github.com/ant-mini-program/api-typings/blob/a98ab78cc376abf22aea5ce9cc1e03c54d7ca62c/packages/my/types/lib.my.d.ts#L10353

**Comment by bytemain** [comment]
@HadesTang 看起来是这几个同步 api 都没设置返回值。
看看怎么修一下

**Comment by bytemain** [comment]
Successfully published:
 - @mini-types/aliauto@3.0.3
 - @mini-types/alipay@3.0.3
 - @mini-types/global@3.0.3
 - @mini-types/my@3.0.3
