### ISSUE TITLE
ci 坏了有没有人修一下？

### ISSUE THREAD

**Issue by Miaonster** [ant-mini-program/api-typings#36]
https://github.com/ant-mini-program/api-typings/actions/runs/4890321882/jobs/8729630497#step:4:70

上次执行是 5.5，修复一下吧，有些新特性 3.0.7 里没有，比如 `getLeftButtonsBoundingClientRect`

**Comment by bytemain** [comment]
好的，我稍后更新一下

**Comment by bytemain** [comment]
新版本已经发布

Successfully published:
 - @mini-types/aliauto@3.0.8
 - @mini-types/alipay@3.0.8
 - @mini-types/global@3.0.8
 - @mini-types/my@3.0.8
