### ISSUE TITLE
Pollution on Props Type In The Component Instance

### ISSUE THREAD

**Issue by lostncg** [ant-mini-program/api-typings#5]
I passed the data into a component props, everything should under my control as I defined the typings, and the typings design is intentional.
Why a type library can force translating my typings into fully optional when the framework's props feature won't mutate my data? 

```ts
interface MyStyle {
  isAMust: string
  pollution: {
    happenes: boolean
  }
}

Component({
  props: {
    /**
     * @type {MyStyle}
     */
    style: null,
  },
  consumer() {
    /**
     * The type now become fully optional???
     * {
     *    isAMust?: string
     *    pollution?: {
     *      happenes?: boolean
     *    }
     * }
     */
    const { style } = this.props;
  },
});
```

The root cause is the usage of` RecursivePartialAndDynamic` type util, may I know why we need it?
https://github.com/ant-mini-program/api-typings/blob/cf14732d1f9a952db2dfcd6fae103f7651c2c322/packages/global/types/lib.global.d.ts#L227

**Comment by bytemain** [comment]
Thanks for the feedback, I will look into it immediately.

**Comment by bytemain** [comment]
We will remove the type utils `RecursivePartialAndDynamic` in `this.data` and `this.props` type inference.

**Comment by bytemain** [comment]
Successfully published:
 - @mini-types/alipay@2.0.0

Thanks for the feedback again!
